-- ============================================================
--  SwiftPOS — Supabase / PostgreSQL Schema
--  Paste this file into the Supabase SQL Editor and run it.
--
--  Notes
--  1. This replaces the old XAMPP/MySQL schema.
--  2. Authentication is handled by Supabase Auth.
--  3. User roles are stored in public.pos_users and enforced by RLS.
--  4. Product categories are tailored for:
--     Fertilizers, Lubricants, Hardware, Feeds, Seeds, Chemicals, Others
-- ============================================================

begin;

create extension if not exists pgcrypto;
create extension if not exists citext;

-- ============================================================
--  ENUMS
-- ============================================================
do $$
begin
  if not exists (select 1 from pg_type where typname = 'app_role') then
    create type public.app_role as enum ('admin', 'staff', 'cashier');
  end if;

  if not exists (select 1 from pg_type where typname = 'user_status') then
    create type public.user_status as enum ('active', 'inactive', 'terminated');
  end if;

  if not exists (select 1 from pg_type where typname = 'branch_status') then
    create type public.branch_status as enum ('active', 'inactive');
  end if;

  if not exists (select 1 from pg_type where typname = 'product_category') then
    create type public.product_category as enum (
      'Fertilizers',
      'Lubricants',
      'Hardware',
      'Feeds',
      'Seeds',
      'Chemicals',
      'Others'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'request_status') then
    create type public.request_status as enum ('pending', 'approved', 'rejected', 'resolved');
  end if;

  if not exists (select 1 from pg_type where typname = 'request_type') then
    create type public.request_type as enum ('manual-request', 'auto-alert');
  end if;
end
$$;

-- ============================================================
--  TABLES
-- ============================================================
create table if not exists public.pos_branches (
  id bigint generated by default as identity primary key,
  name text not null unique,
  branch_number text unique,
  address text,
  contact_number text,
  status public.branch_status not null default 'active',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.pos_users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  username citext not null unique,
  fullname text not null,
  email citext unique,
  contact_number text,
  role public.app_role not null default 'cashier',
  status public.user_status not null default 'active',
  branch_id bigint references public.pos_branches(id) on delete set null,
  failed_attempts integer not null default 0 check (failed_attempts >= 0),
  locked_until timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.pos_items (
  id bigint generated by default as identity primary key,
  name text not null,
  product_number text unique,
  emoji text default '🏷️',
  price numeric(12,2) not null default 0.00 check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  category public.product_category not null default 'Others',
  branch_id bigint references public.pos_branches(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.pos_sales (
  id text primary key,
  sold_at timestamptz not null default timezone('utc', now()),
  cashier_user_id bigint references public.pos_users(id) on delete set null,
  cashier text not null,
  cashier_name text,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric(12,2) not null default 0.00 check (subtotal >= 0),
  tax numeric(12,2) not null default 0.00 check (tax >= 0),
  discount_type text,
  discount_amt numeric(12,2) not null default 0.00 check (discount_amt >= 0),
  total numeric(12,2) not null default 0.00 check (total >= 0),
  cash numeric(12,2) not null default 0.00 check (cash >= 0),
  change numeric(12,2) not null default 0.00,
  status text not null default 'completed',
  branch_id bigint references public.pos_branches(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.pos_requests (
  id bigint generated by default as identity primary key,
  item_id bigint references public.pos_items(id) on delete set null,
  item_name text not null,
  stock integer not null default 0 check (stock >= 0),
  type public.request_type not null default 'manual-request',
  requested_by_user_id bigint references public.pos_users(id) on delete set null,
  requested_by text not null,
  requested_by_name text,
  note text,
  status public.request_status not null default 'pending',
  requested_at timestamptz not null default timezone('utc', now()),
  branch_id bigint references public.pos_branches(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.pos_cashier_daily_summary (
  id bigint generated by default as identity primary key,
  sales_date date not null,
  cashier_user_id bigint not null references public.pos_users(id) on delete cascade,
  cashier text not null,
  cashier_name text,
  branch_id bigint not null references public.pos_branches(id) on delete cascade,
  transactions integer not null default 0 check (transactions >= 0),
  items_sold integer not null default 0 check (items_sold >= 0),
  total_sales numeric(12,2) not null default 0.00 check (total_sales >= 0),
  starting_cash numeric(12,2) check (starting_cash is null or starting_cash >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint uq_cashier_date_branch unique (sales_date, cashier_user_id, branch_id)
);

create table if not exists public.pos_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id bigint references public.pos_users(id) on delete set null,
  username text not null,
  fullname text not null,
  role public.app_role,
  action text not null,
  category text not null,
  description text,
  meta jsonb,
  branch_id bigint references public.pos_branches(id) on delete set null,
  logged_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.pos_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default timezone('utc', now())
);

-- ============================================================
--  INDEXES
-- ============================================================
create index if not exists idx_pos_users_auth_user_id on public.pos_users(auth_user_id);
create index if not exists idx_pos_users_branch_id on public.pos_users(branch_id);
create index if not exists idx_pos_users_role on public.pos_users(role);

create index if not exists idx_pos_items_branch_id on public.pos_items(branch_id);
create index if not exists idx_pos_items_category on public.pos_items(category);
create index if not exists idx_pos_items_name on public.pos_items(name);

create index if not exists idx_pos_sales_sold_at on public.pos_sales(sold_at desc);
create index if not exists idx_pos_sales_branch_id on public.pos_sales(branch_id);
create index if not exists idx_pos_sales_cashier_user_id on public.pos_sales(cashier_user_id);

create index if not exists idx_pos_requests_branch_id on public.pos_requests(branch_id);
create index if not exists idx_pos_requests_status on public.pos_requests(status);
create index if not exists idx_pos_requests_requested_at on public.pos_requests(requested_at desc);

create index if not exists idx_pos_summary_branch_date on public.pos_cashier_daily_summary(branch_id, sales_date desc);
create index if not exists idx_pos_audit_branch_logged on public.pos_audit_log(branch_id, logged_at desc);
create index if not exists idx_pos_audit_actor on public.pos_audit_log(actor_user_id);

-- ============================================================
--  TRIGGERS / HELPERS
-- ============================================================
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_pos_branches_updated_at on public.pos_branches;
create trigger trg_pos_branches_updated_at
before update on public.pos_branches
for each row
execute function public.set_updated_at();

drop trigger if exists trg_pos_users_updated_at on public.pos_users;
create trigger trg_pos_users_updated_at
before update on public.pos_users
for each row
execute function public.set_updated_at();

drop trigger if exists trg_pos_items_updated_at on public.pos_items;
create trigger trg_pos_items_updated_at
before update on public.pos_items
for each row
execute function public.set_updated_at();

drop trigger if exists trg_pos_summary_updated_at on public.pos_cashier_daily_summary;
create trigger trg_pos_summary_updated_at
before update on public.pos_cashier_daily_summary
for each row
execute function public.set_updated_at();

create or replace function public.sync_pos_user_from_auth()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  requested_role text;
  requested_branch bigint;
  requested_status text;
  derived_username text;
  derived_fullname text;
begin
  requested_role := lower(
    coalesce(
      new.raw_app_meta_data ->> 'role',
      new.raw_user_meta_data ->> 'role',
      'cashier'
    )
  );

  requested_status := lower(
    coalesce(
      new.raw_app_meta_data ->> 'status',
      new.raw_user_meta_data ->> 'status',
      'active'
    )
  );

  begin
    requested_branch := nullif(
      coalesce(
        new.raw_app_meta_data ->> 'branch_id',
        new.raw_user_meta_data ->> 'branch_id',
        ''
      ),
      ''
    )::bigint;
  exception
    when others then requested_branch := null;
  end;

  derived_username := coalesce(
    nullif(new.raw_user_meta_data ->> 'username', ''),
    split_part(coalesce(new.email, 'user_' || replace(new.id::text, '-', '')), '@', 1)
  );

  derived_fullname := coalesce(
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    nullif(new.raw_user_meta_data ->> 'fullname', ''),
    split_part(coalesce(new.email, 'User'), '@', 1)
  );

  insert into public.pos_users (
    auth_user_id,
    username,
    fullname,
    email,
    role,
    status,
    branch_id
  )
  values (
    new.id,
    derived_username,
    derived_fullname,
    nullif(new.email, ''),
    case
      when requested_role in ('admin', 'staff', 'cashier') then requested_role::public.app_role
      else 'cashier'::public.app_role
    end,
    case
      when requested_status in ('active', 'inactive', 'terminated') then requested_status::public.user_status
      else 'active'::public.user_status
    end,
    requested_branch
  )
  on conflict (auth_user_id) do update
    set username = excluded.username,
        fullname = excluded.fullname,
        email = excluded.email,
        role = excluded.role,
        status = excluded.status,
        branch_id = coalesce(excluded.branch_id, public.pos_users.branch_id);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_swiftpos on auth.users;
create trigger on_auth_user_created_swiftpos
after insert on auth.users
for each row
execute function public.sync_pos_user_from_auth();

drop trigger if exists on_auth_user_updated_swiftpos on auth.users;
create trigger on_auth_user_updated_swiftpos
after update on auth.users
for each row
execute function public.sync_pos_user_from_auth();

create or replace function public.sync_all_pos_users_from_auth()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  auth_row auth.users%rowtype;
begin
  for auth_row in select * from auth.users loop
    insert into public.pos_users (
      auth_user_id,
      username,
      fullname,
      email,
      role,
      status,
      branch_id
    )
    values (
      auth_row.id,
      coalesce(
        nullif(auth_row.raw_user_meta_data ->> 'username', ''),
        split_part(coalesce(auth_row.email, 'user_' || replace(auth_row.id::text, '-', '')), '@', 1)
      ),
      coalesce(
        nullif(auth_row.raw_user_meta_data ->> 'full_name', ''),
        nullif(auth_row.raw_user_meta_data ->> 'fullname', ''),
        split_part(coalesce(auth_row.email, 'User'), '@', 1)
      ),
      nullif(auth_row.email, ''),
      case
        when lower(coalesce(auth_row.raw_app_meta_data ->> 'role', auth_row.raw_user_meta_data ->> 'role', 'cashier')) in ('admin', 'staff', 'cashier')
          then lower(coalesce(auth_row.raw_app_meta_data ->> 'role', auth_row.raw_user_meta_data ->> 'role', 'cashier'))::public.app_role
        else 'cashier'::public.app_role
      end,
      case
        when lower(coalesce(auth_row.raw_app_meta_data ->> 'status', auth_row.raw_user_meta_data ->> 'status', 'active')) in ('active', 'inactive', 'terminated')
          then lower(coalesce(auth_row.raw_app_meta_data ->> 'status', auth_row.raw_user_meta_data ->> 'status', 'active'))::public.user_status
        else 'active'::public.user_status
      end,
      nullif(coalesce(auth_row.raw_app_meta_data ->> 'branch_id', auth_row.raw_user_meta_data ->> 'branch_id', ''), '')::bigint
    )
    on conflict (auth_user_id) do update
      set username = excluded.username,
          fullname = excluded.fullname,
          email = excluded.email,
          role = excluded.role,
          status = excluded.status,
          branch_id = excluded.branch_id;
  end loop;
end;
$$;

-- ============================================================
--  RLS HELPER FUNCTIONS
-- ============================================================
create or replace function public.current_pos_user_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select id
  from public.pos_users
  where auth_user_id = auth.uid()
  limit 1
$$;

create or replace function public.current_app_role()
returns public.app_role
language sql
stable
security definer
set search_path = public
as $$
  select role
  from public.pos_users
  where auth_user_id = auth.uid()
  limit 1
$$;

create or replace function public.current_branch_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select branch_id
  from public.pos_users
  where auth_user_id = auth.uid()
  limit 1
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_app_role() = 'admin', false)
$$;

create or replace function public.same_branch(target_branch_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.is_admin()
    or target_branch_id is null
    or target_branch_id = public.current_branch_id()
$$;

-- ============================================================
--  RLS
-- ============================================================
alter table public.pos_branches enable row level security;
alter table public.pos_users enable row level security;
alter table public.pos_items enable row level security;
alter table public.pos_sales enable row level security;
alter table public.pos_requests enable row level security;
alter table public.pos_cashier_daily_summary enable row level security;
alter table public.pos_audit_log enable row level security;
alter table public.pos_settings enable row level security;

-- Branches
drop policy if exists "branches_select_authenticated" on public.pos_branches;
create policy "branches_select_authenticated"
on public.pos_branches
for select
to authenticated
using (status = 'active' or public.is_admin());

drop policy if exists "branches_admin_manage" on public.pos_branches;
create policy "branches_admin_manage"
on public.pos_branches
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Users
drop policy if exists "users_select_self_admin_or_branch" on public.pos_users;
create policy "users_select_self_admin_or_branch"
on public.pos_users
for select
to authenticated
using (
  public.is_admin()
  or auth_user_id = auth.uid()
  or (
    public.current_app_role() in ('staff', 'cashier')
    and branch_id = public.current_branch_id()
    and status = 'active'
  )
);

drop policy if exists "users_admin_manage" on public.pos_users;
create policy "users_admin_manage"
on public.pos_users
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Items
drop policy if exists "items_read_by_role" on public.pos_items;
create policy "items_read_by_role"
on public.pos_items
for select
to authenticated
using (public.same_branch(branch_id));

drop policy if exists "items_admin_staff_insert" on public.pos_items;
create policy "items_admin_staff_insert"
on public.pos_items
for insert
to authenticated
with check (
  public.is_admin()
  or (
    public.current_app_role() = 'staff'
    and public.same_branch(branch_id)
  )
);

drop policy if exists "items_admin_staff_update" on public.pos_items;
create policy "items_admin_staff_update"
on public.pos_items
for update
to authenticated
using (
  public.is_admin()
  or (
    public.current_app_role() = 'staff'
    and public.same_branch(branch_id)
  )
)
with check (
  public.is_admin()
  or (
    public.current_app_role() = 'staff'
    and public.same_branch(branch_id)
  )
);

drop policy if exists "items_admin_staff_delete" on public.pos_items;
create policy "items_admin_staff_delete"
on public.pos_items
for delete
to authenticated
using (
  public.is_admin()
  or (
    public.current_app_role() = 'staff'
    and public.same_branch(branch_id)
  )
);

-- Sales
drop policy if exists "sales_select_by_role" on public.pos_sales;
create policy "sales_select_by_role"
on public.pos_sales
for select
to authenticated
using (
  public.is_admin()
  or branch_id = public.current_branch_id()
  or cashier_user_id = public.current_pos_user_id()
);

drop policy if exists "sales_insert_by_branch_user" on public.pos_sales;
create policy "sales_insert_by_branch_user"
on public.pos_sales
for insert
to authenticated
with check (
  public.is_admin()
  or (
    public.current_app_role() in ('staff', 'cashier')
    and branch_id = public.current_branch_id()
    and cashier_user_id = public.current_pos_user_id()
  )
);

drop policy if exists "sales_admin_update_delete" on public.pos_sales;
create policy "sales_admin_update_delete"
on public.pos_sales
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Requests
drop policy if exists "requests_select_by_branch" on public.pos_requests;
create policy "requests_select_by_branch"
on public.pos_requests
for select
to authenticated
using (public.same_branch(branch_id));

drop policy if exists "requests_insert_by_role" on public.pos_requests;
create policy "requests_insert_by_role"
on public.pos_requests
for insert
to authenticated
with check (
  public.is_admin()
  or (
    public.current_app_role() in ('staff', 'cashier')
    and branch_id = public.current_branch_id()
    and requested_by_user_id = public.current_pos_user_id()
  )
);

drop policy if exists "requests_admin_staff_update" on public.pos_requests;
create policy "requests_admin_staff_update"
on public.pos_requests
for update
to authenticated
using (
  public.is_admin()
  or (
    public.current_app_role() = 'staff'
    and branch_id = public.current_branch_id()
  )
)
with check (
  public.is_admin()
  or (
    public.current_app_role() = 'staff'
    and branch_id = public.current_branch_id()
  )
);

drop policy if exists "requests_admin_delete" on public.pos_requests;
create policy "requests_admin_delete"
on public.pos_requests
for delete
to authenticated
using (public.is_admin());

-- Cashier daily summary
drop policy if exists "summary_select_by_role" on public.pos_cashier_daily_summary;
create policy "summary_select_by_role"
on public.pos_cashier_daily_summary
for select
to authenticated
using (
  public.is_admin()
  or branch_id = public.current_branch_id()
  or cashier_user_id = public.current_pos_user_id()
);

drop policy if exists "summary_insert_by_role" on public.pos_cashier_daily_summary;
create policy "summary_insert_by_role"
on public.pos_cashier_daily_summary
for insert
to authenticated
with check (
  public.is_admin()
  or (
    cashier_user_id = public.current_pos_user_id()
    and branch_id = public.current_branch_id()
  )
);

drop policy if exists "summary_update_by_role" on public.pos_cashier_daily_summary;
create policy "summary_update_by_role"
on public.pos_cashier_daily_summary
for update
to authenticated
using (
  public.is_admin()
  or (
    cashier_user_id = public.current_pos_user_id()
    and branch_id = public.current_branch_id()
  )
)
with check (
  public.is_admin()
  or (
    cashier_user_id = public.current_pos_user_id()
    and branch_id = public.current_branch_id()
  )
);

-- Audit log
drop policy if exists "audit_select_by_role" on public.pos_audit_log;
create policy "audit_select_by_role"
on public.pos_audit_log
for select
to authenticated
using (
  public.is_admin()
  or branch_id = public.current_branch_id()
  or actor_user_id = public.current_pos_user_id()
);

drop policy if exists "audit_insert_by_role" on public.pos_audit_log;
create policy "audit_insert_by_role"
on public.pos_audit_log
for insert
to authenticated
with check (
  public.is_admin()
  or (
    actor_user_id = public.current_pos_user_id()
    and public.same_branch(branch_id)
  )
);

-- Settings
drop policy if exists "settings_read_authenticated" on public.pos_settings;
create policy "settings_read_authenticated"
on public.pos_settings
for select
to authenticated
using (true);

drop policy if exists "settings_admin_manage" on public.pos_settings;
create policy "settings_admin_manage"
on public.pos_settings
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- ============================================================
--  SEED DATA
-- ============================================================
insert into public.pos_branches (name, branch_number, address, contact_number, status)
values
  ('Main Branch', '001', 'Main Street', '09170000001', 'active'),
  ('Branch 2', '002', 'Second Avenue', '09170000002', 'active')
on conflict (name) do update
set branch_number = excluded.branch_number,
    address = excluded.address,
    contact_number = excluded.contact_number,
    status = excluded.status;

insert into public.pos_items (name, product_number, emoji, price, stock, category, branch_id)
values
  ('Urea Fertilizer 50kg', 'FERT-001', '🌾', 1450.00, 40, 'Fertilizers', 1),
  ('Engine Oil 1L', 'LUBE-001', '🛢️', 320.00, 60, 'Lubricants', 1),
  ('GI Tie Wire', 'HARD-001', '🔩', 95.00, 120, 'Hardware', 1),
  ('Broiler Feeds 25kg', 'FEED-001', '🐔', 1180.00, 35, 'Feeds', 1),
  ('Hybrid Corn Seeds', 'SEED-001', '🌽', 280.00, 75, 'Seeds', 1),
  ('Insecticide 500ml', 'CHEM-001', '🧪', 410.00, 50, 'Chemicals', 1),
  ('Misc Farm Supply', 'OTHR-001', '📦', 150.00, 20, 'Others', null)
on conflict (product_number) do update
set name = excluded.name,
    emoji = excluded.emoji,
    price = excluded.price,
    stock = excluded.stock,
    category = excluded.category,
    branch_id = excluded.branch_id;

insert into public.pos_settings (key, value)
values
  ('stock_threshold', '5')
on conflict (key) do update
set value = excluded.value,
    updated_at = timezone('utc', now());

commit;

-- ============================================================
--  AFTER RUNNING THIS SCHEMA
-- ============================================================
-- Create your auth users in Supabase Authentication first, then assign roles:
--
-- Option A: assign access levels directly in Supabase Auth metadata:
--
-- update auth.users
-- set raw_app_meta_data =
--   coalesce(raw_app_meta_data, '{}'::jsonb)
--   || jsonb_build_object('role', 'admin', 'status', 'active'),
--     raw_user_meta_data =
--   coalesce(raw_user_meta_data, '{}'::jsonb)
--   || jsonb_build_object('username', 'admin', 'full_name', 'Administrator')
-- where email = 'admin@swiftpos.local';
--
-- update auth.users
-- set raw_app_meta_data =
--   coalesce(raw_app_meta_data, '{}'::jsonb)
--   || jsonb_build_object('role', 'staff', 'status', 'active', 'branch_id', 1),
--     raw_user_meta_data =
--   coalesce(raw_user_meta_data, '{}'::jsonb)
--   || jsonb_build_object('username', 'staff1', 'full_name', 'Staff One')
-- where email = 'staff1@swiftpos.local';
--
-- update auth.users
-- set raw_app_meta_data =
--   coalesce(raw_app_meta_data, '{}'::jsonb)
--   || jsonb_build_object('role', 'cashier', 'status', 'active', 'branch_id', 1),
--     raw_user_meta_data =
--   coalesce(raw_user_meta_data, '{}'::jsonb)
--   || jsonb_build_object('username', 'cashier1', 'full_name', 'Cashier One')
-- where email = 'cashier1@swiftpos.local';
--
-- Then resync all auth users into public.pos_users:
--
-- select public.sync_all_pos_users_from_auth();
--
-- Because Supabase Auth already manages passwords securely,
-- there is intentionally no plain-text password column here.
